apiVersion: v1
kind: Pod
metadata:
  name: op-sidecar
  namespace: default
spec:
  serviceAccountName: op-sidecar
  containers:
  - name: op-sidecar
    image: mes24x7/op_sidecar:latest
    imagePullPolicy: Always
    command: ["sleep"]
    args: ["100000"]        
