#!/bin/bash
curl https://raw.githubusercontent.com/kubernetes/helm/master/scripts/get > get_helm.sh
chmod 700 get_helm.sh
export PATH="$PATH:/usr/local/bin"
./get_helm.sh
kubectl create serviceaccount --namespace kube-system tiller
kubectl create clusterrolebinding tiller-cluster-rule --clusterrole=cluster-admin --serviceaccount=kube-system:tiller
helm init --service-account tiller
helm plugin install https://github.com/hypnoglow/helm-s3.git
helm repo add paysafe-aws-charts s3://paysafe-aws-charts/charts
helm repo list
helm repo update
